name: Linux Tailscale VPN Server

on:
  workflow_dispatch:

jobs:
  vpn-server:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Enable IP Forwarding
        run: |
          sudo sysctl -w net.ipv4.ip_forward=1
          sudo sysctl -w net.ipv6.conf.all.forwarding=1

      - name: 2. Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: 3. Connect to Tailscale
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
        run: |
          sudo tailscale up \
            --authkey="${TAILSCALE_AUTHKEY}" \
            --advertise-exit-node \
            --accept-dns=true \
            --hostname=github-vpn-node \
            --port=41641 \
            --reset

      - name: 4. Keep Alive
        run: |
          echo "VPN Server is running as an Exit Node..."
          sleep 21600
